### ISSUE TITLE
negative profit

### ISSUE THREAD

**Issue by zaza81** [paco0x/amm-arbitrageur#13]
how can I get negative profit?

<img width="510" alt="Screenshot 2021-05-07 at 12 20 33" src="https://user-images.githubusercontent.com/1845515/117436103-e0372980-af2e-11eb-94ff-ce3c70f86853.png">

Is this due to fees?

**Comment by paco0x** [comment]
Yes, the profit calculation in the bot codes does count the gas fees. So you may see a negative profit.

profit = PROFIT_ON_CHAIN - GAS_COSTS
