### ISSUE TITLE
我监控一些小众的币，要添加哪几个地方呀？

### ISSUE THREAD

**Issue by tutan123** [paco0x/amm-arbitrageur#14]
你好，比如我想监控一些safe，动物系列的币。 tokens.ts和pair-bsc.json都要改么？ 要加些什么呢？

**Comment by tutan123** [comment]
还有，另外你说的那个
“For example: Use your own node or a private node to get low latency on network requests. ”
我看只有部署合约的时候用到了httpprovider地址 , 这个在部署完合约正式运行节点的时候，要怎么提速呀，比如怎么用quiknode那些节点

**Comment by paco0x** [comment]
> 你好，比如我想监控一些safe，动物系列的币。 tokens.ts和pair-bsc.json都要改么？ 要加些什么呢？

现在 bot 代码的逻辑是：如果 `pair-bsc.json` 存在，就直接使用这个文件中的交易对，否则就从 `tokens.ts` 中的 token 列表自动查找并生成一个 `pair-bsc.json`. 以供下次使用。所以你可以删掉 `pair-bsc.json` 然后重新编辑 `tokens.ts`，加上你想要监控的代币。

建议监控更少的代币对，因为这样可以更频繁的监控这些代币对的价格变化，效率会更高。

**Comment by paco0x** [comment]
> 还有，另外你说的那个
> “For example: Use your own node or a private node to get low latency on network requests. ”
> 我看只有部署合约的时候用到了httpprovider地址 , 这个在部署完合约正式运行节点的时候，要怎么提速呀，比如怎么用quiknode那些节点

bot 也是使用的 hardhat 配置文件里的 provider. 修改配置文件里的就行了。
