### ISSUE TITLE
这个项目可不可以用到CHI Gastoken

### ISSUE THREAD

**Issue by tutan123** [paco0x/amm-arbitrageur#15]
1. 看到一些bot，有用到chi token用来支付gas费，从而减少很多gas,请问这个代码怎么修改可以做到这点呀.
2. 类似下面这个bot，成功率很高，请问怎么可以做到提高成功率？
3. 类似下面这个bot，为什么要先转成busd再转成bnb?
![image](https://user-images.githubusercontent.com/9970427/117598768-051fdc80-b17b-11eb-9b59-5f5d886474bc.png)

**Comment by paco0x** [comment]
1. 这个当初是适配的 BSC，以太坊上确实可以用 chi，需要你自己实现，参考：https://soliditydeveloper.com/chi-gas
2. 可以参考下首页的 readme，观察其他 bot 的行为学习也是可以的
3. 这个看不出来，可以贴个 tx 链接出来

**Comment by tutan123** [comment]
https://bscscan.com/tx/0x3fd5739d4e963a7d335db74a824debc23d2ae7e47ad79d166242a0987583439d

像这种，单次profit少,成功率高。这个五次swap在一个transaction里面，当前这个bot支持这种多次swap么。

**Comment by paco0x** [comment]
它是在 pancake v1 和 v2 之间做套利，可能竞争少
