### ISSUE TITLE
Contract owner can call withdraw() to withdraw the profit.

### ISSUE THREAD

**Issue by tutan123** [paco0x/amm-arbitrageur#16]
前面那个issue关掉了呀，请问一下： 要怎么把赚到的token从合约里提出来？ 是要先verify合约代码，还是直接用什么命令直接通过js代码提取呢？

**Comment by paco0x** [comment]
调用 withdraw()，会把合约里的 ETH/BNB 或 erc20 转给 owner

**Comment by ccoop1** [comment]
I don’t speak good Chinese and I believe this is a separate issue but the title of this - clearly exposes a reentrancy attack point and this can easily be addressed. Be careful deploying without addressing this issue.
