### ISSUE TITLE
请问要怎么调用withdraw呀

### ISSUE THREAD

**Issue by tutan123** [paco0x/amm-arbitrageur#18]
当前我用we3.py包来用Python调用这个合约，想withdraw，当时因为它的合约没有验证，所以abi显示不出来，我就在python里面创建不了contract对象，接着无法调用withdraw了。

作者您好，请问怎么调用withdraw呢？ 可以写个加个withdraw功能在github的bot里面，或者web3.py版本的脚本？
可以大概讲一下

**Comment by tutan123** [comment]
![image](https://user-images.githubusercontent.com/9970427/118355069-b28e5800-b5a0-11eb-855a-315d6bdab342.png)
好像加一行这个await就ok了，只是Python里面好像实现不了

**Comment by tutan123** [comment]
需要把钱先打到合约里面吗？

**Comment by paco0x** [comment]
withdraw 是合约里有币的时候执行的。python 的话要加载下 abi，`hardhat compile` 之后 `artifacts` 目录下有 abi 文件

**Comment by tutan123** [comment]
那启动这个bot，是不是要往合约里面先打一笔钱进去呢？还是直接调用owner账户里面的bnb就行了？

**Comment by paco0x** [comment]
不需要打钱，合约全部用的闪电贷，不需要成本

**Comment by tutan123** [comment]
gas费是从owner里面出还是flashloan,还是合约呀

**Comment by paco0x** [comment]
调用合约的账户
