### ISSUE TITLE
All transactions getting error

### ISSUE THREAD

**Issue by edgybtc** [paco0x/amm-arbitrageur#23]
You can find the contract here:
https://bscscan.com/address/0x9523719805da3c7123f8379f1e82c8e33b993595

The first transaction was reverted with an error: No Profit
But then all the succeeding transactions are reverted without giving any reason. Is there an error in the code? Or am I doing something wrong?

**Comment by paco0x** [comment]
This might be caused by the latency. When the bot finds a profitable opportunity, it sends a transaction to the network. During the mining process, other bots may get also send their transaction and get handled first.

On bsc, it better to set a lower profit threshold since the gas is low.

**Comment by edgybtc** [comment]
> This might be caused by the latency. When the bot finds a profitable opportunity, it sends a transaction to the network. During the mining process, other bots may get also send their transaction and get handled first.
> 
> On bsc, it better to set a lower profit threshold since the gas is low.

Thanks for replying. Will increasing the gas fees be of any help? And can you please advise on how the latency can be reduced. 
I have connected the bot to a local node rpc, but I am still getting 450ms on flashswipe.

**Comment by paco0x** [comment]
From what I see, the bots run with low gas and low profit, but with more frequent txs on BSC/heco. But on ETH, it's better to set a higher profit target and send with higher gas.
