### ISSUE TITLE
Hardhat test

### ISSUE THREAD

**Issue by ktorrentk** [paco0x/amm-arbitrageur#41]
hi all
    i have a question when i run hardhat test it's show error log below.  Who's can tell me how to solve it.
MathTest
    #sqrt
      1) "before each" hook for "calculate square root correctly with small input"

  Flashswap
    flash swap arbitrage
      2) "before all" hook for "do flash swap between Pancake and MDEX"

**Comment by paco0x** [comment]
Sorry, I'm maintaining this repo. The test cases rely on the mainnet fork, there may be something different and you need to figure out it by yourself.
