### ISSUE TITLE
Couldn't find ethers-v5

### ISSUE THREAD

**Issue by blademckain** [paco0x/amm-arbitrageur#5]
Hi all,
i am trying to deploy this project but i get this error

``
Creating Typechain artifacts in directory typechain for target ethers-v5
An unexpected error occurred:

Error: Couldn't find ethers-v5. Tried loading: @typechain/ethers-v5, typechain-t                                                                     arget-ethers-v5, /root/Desktop/amm-arbitrageur/ethers-v5.
Perhaps you forgot to install @typechain/ethers-v5?
``

i have already do
``
npm i @typechain/ethers-v5
npm i typechain-target-ethers-v5
``

**Comment by paco0x** [comment]
Could you try: `yarn install` and `yarn install -D`

**Comment by blademckain** [comment]
yeah this solve the issue
thx
