### ISSUE TITLE
how to edit bot/config.ts

### ISSUE THREAD

**Issue by blademckain** [paco0x/amm-arbitrageur#6]
how should the
bot/config.ts file be configured?
``
const contractAddr = my address wallet ??

``

**Comment by paco0x** [comment]
It's the contract address you deployed.

**Comment by blademckain** [comment]
the same i put in .secret.ts
right?

**Comment by paco0x** [comment]
No. You need to deploy the `FlashBot` contract first by using the deploy script. It generates a contract address which will be printed on the screen after you deployed it. Or you can use block explorer to find out that address.

**Comment by blademckain** [comment]
ok i run 
``
 npx hardhat run scripts/deploy.ts --network bsc
``

then copy the contract address in bot/config.ts

next run

``
yarn run bot
``

correct?

**Comment by paco0x** [comment]
> ok i run
> `npx hardhat run scripts/deploy.ts --network bsc`
> 
> then copy the contract address in bot/config.ts
> 
> next run
> 
> `yarn run bot`
> 
> correct?

Yes. And please update to the latest code to redeploy the contract. There's a bug in the contract constructor param in the previous code. 

Reminder: This is a project just for demonstration purposes. Documentation is not sufficient so you'd better have some knowledge to modify the codes or configs to fulfill the requirements by yourself.
