### ISSUE TITLE
deployer  address

### ISSUE THREAD

**Issue by zorrosword** [paco0x/amm-arbitrageur#7]
deploy.ts  中 const flashBot = await FlashBot.deploy(deployer.address) 的  deployer.address  我填写的是自己的钱包地址，
看到 flashbot.sol中，这个地址应该是 weth（wbnb）的地址
 constructor(address _WETH) {
        WETH = _WETH;
        baseTokens.add(_WETH);
    }
是否存在问题？

**Comment by paco0x** [comment]
对，写错了，应该是 WETH 或者 WBNB 地址
