### ISSUE TITLE
error TS2345: Argument of type 'BigNumber' is not assignable to parameter of type 'BigNumberish'

### ISSUE THREAD

**Issue by blademckain** [paco0x/amm-arbitrageur#8]
i get this error when try to test

``
npx hardhat test
Creating Typechain artifacts in directory typechain for target ethers-v5
Successfully generated Typechain artifacts!
An unexpected error occurred:

test/AccessControlTest.ts:45:39 - error TS2345: Argument of type 'BigNumber' is not assignable to parameter of type 'BigNumberish'.
  Type 'import("/root/Desktop/amm-arbitrageur/node_modules/@ethersproject/bignumber/lib/bignumber").BigNumber' is not assignable to type 'import("/root/Desktop/amm-arbitrageur/node_modules/ethers/node_modules/@ethersproject/bignumber/lib/bignumber").BigNumber'.
    The types returned by 'toBigInt()' are incompatible between these types.
      Type 'BigInt' is not assignable to type 'bigint'.

45     await weth.mint(flashBot.address, wethAmount);
                                         ~~~~~~~~~~
test/AccessControlTest.ts:58:59 - error TS2345: Argument of type 'BigNumber' is not assignable to parameter of type 'BigNumberish'.

58     expect(wethBlanceAfter).to.be.eq(wethBlanceBefore.add(wethAmount));
                                                             ~~~~~~~~~~
``

**Comment by paco0x** [comment]
This might be caused by wrong deps version. Try cleaning up the node_modules and reinstall by:

```
yarn install -D
```

**Comment by blademckain** [comment]
I tried to delete the node_modules and cache folder and give the command again:
yarn install -D

but have the same error

i try to redo all git clone and test
