### ISSUE TITLE
transaction failed

### ISSUE THREAD

**Issue by SebastienV31** [paco0x/amm-arbitrageur#9]
Hi,
I have this issue when the bot tryies to make an arbitrage 
transaction failed (transactionHash="0x3ee297138a54934523064664b92fe10365df7f3e7f15443735da6e65bb3d52cc", transaction={"hash":"0x3ee297138a54934523064664b92fe10365df7f3e7f15443735da6e65bb3d52cc","type":null,"accessList":null,"blockHash":null,"blockNumber":null,"transactionIndex":null,"confirmations":0,"from":"0x7eA23185A79895fE4717d050Ae18AcA6da1934DC","gasPrice":{"type":"BigNumber","hex":"0x02540be400"},"gasLimit":{"type":"BigNumber","hex":"0x0493e0"},"to":"0x9b41E94846B73a983f76601Fb8d285f78ba59A15","value":{"type":"BigNumber","hex":"0x00"},"nonce":120,"data":"0xbaee64f10000000000000000000000000aa4b9be1dbb8cbca7bbddddb4f30894b1afe85b000000000000000000000000229e9f691ed34cf4cb706fae7bf65aeb9020e329","r":"0xd59eec24cf9e3f47d0f3db34937d47ff68204b006d83bf0c09ce3e609cf11203","s":"0x02ad5c73f62763de3d18754f0031f086428a32432b07bf4410a3acd9273f3111","v":147,"creates":null,"chainId":56}, receipt={"to":"0x9b41E94846B73a983f76601Fb8d285f78ba59A15","from":"0x7eA23185A79895fE4717d050Ae18AcA6da1934DC","contractAddress":null,"transactionIndex":10,"gasUsed":{"type":"BigNumber","hex":"0x012c17"},"logsBloom":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","blockHash":"0xa8832e56440749f085fa5459bc4a55f0835d6ca4fae6d211d96c61f83339a1d7","transactionHash":"0x3ee297138a54934523064664b92fe10365df7f3e7f15443735da6e65bb3d52cc","logs":[],"blockNumber":7128396,"confirmations":2,"cumulativeGasUsed":{"type":"BigNumber","hex":"0x18e321"},"status":0,"byzantium":true}, code=CALL_EXCEPTION, version=providers/5.1.0) 
Could you help me with that please ?

**Comment by paco0x** [comment]
This failure means the profit was taken by other arbitrageurs so you might have no profit when your transaction gets processed. You can see in the transaction explorer, it says: `'Arbitrage fail, no profit'`. 

Because there are too many arb bots running in the network. My suggestion is: try to optimize the bot code by increasing gas price and monitoring lesser token pairs. So your transaction can be handled more quickly and the possibility of getting profit increases.

**Comment by SebastienV31** [comment]
Thank you for your quick answer, great bot by the way !
